[package]
name = "arzamas"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "migration", "entity"]

[lib]
path = "src/lib.rs"
name = "lib"

[[bin]]
path = "src/main.rs"
name = "bin"

[dependencies]
actix-web = "4.3.0"
actix-http = "3.3.0"
actix-files = "0.6.2"
actix-service = "2.0"
actix-session = { version = "0.7.2", features = ["redis-rs-session", "redis-rs-tls-session"] }
actix-cors = "0.6.4"
actix-identity = "0.5.2"
dotenv = "0.15.0"
secrecy = { version = "0.8", features = ["serde"] }
serde_json = "1.0.93"
serde = { version = "1.0.152", features = ["derive"] }
serde_derive = "1.0.152"
jsonwebtoken = "8.2.0"

futures = "0.3.26"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }

tracing = { version = "0.1.37", features = ["log"] }
tracing-actix-web = "0.7.2"
tracing-bunyan-formatter = "0.3.6"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.16", features = ["registry", "env-filter"] }
tracing-appender = "0.2.2"
log = { version = "0.4.17", features = ["max_level_debug", "release_max_level_info"] }

redis = { version = "0.22.3", features = ["tokio-comp", "tokio-native-tls-comp", "connection-manager"] }

chrono = "0.4.23"
hex = "0.4.3"
sha2 = "0.10.6"
regex = "1.7.1"
rust-argon2 = "1.0.0"
lazy_static = "1.4.0"
unicode-normalization = "0.1.22"
getrandom = "0.2.1"
time = "0.3.19"
async_once="0.2.6"
tokio-async-std = "1.5.3"
uuid = { version = "1.3.0", features = [ "v4" ] }
rand = "0.8.5"

entity = { path = "entity" }
migration = { path = "migration" }

[dependencies.sea-orm]
version = "0.11.0"
default-features = true
features = ["mock", "default", "with-json", "macros", "sqlx-postgres", "runtime-actix-rustls", "chrono", "postgres-array"]

[dev-dependencies]
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
reqwest = { version = "0.11.14", features = ["json"] }
once_cell = "1.17.1"
uuid = { version = "1.3.0", features = ["v4"] }
serde_json = "1.0.93"

[dev-dependencies.sqlx]
version = "0.6.2"
default-features = false
features = [
    "runtime-actix-rustls",
    "postgres",
]

[dependencies.lettre]
version = "0.10.3"
default-features = false
features = [
    "smtp-transport",
    "tokio1",
    "native-tls",
    "tokio1-native-tls",
    "hostname",
    "builder",
    "tracing",
]