[package]
name = "arzamas"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "migration", "entity"]

[lib]
path = "src/lib.rs"
name = "lib"

[[bin]]
path = "src/main.rs"
name = "bin"

[dependencies]
actix-web = "4.2.1"
actix-http = "3.2.2"
actix-files = "0.6.2"
actix-service = "2.0.2"
dotenv = "0.15.0"
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive"] }

futures = "0.3.25"
tokio = { version = "1.23.0", features = ["macros", "rt-multi-thread"] }
tracing = { version = "0.1.36", features = ["log"] }
tracing-actix-web = "0.7.1"
tracing-bunyan-formatter = "0.3.4"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.16", features = ["registry", "env-filter"] }
tracing-appender = "0.2.2"
log = { version = "0.4.17", features = ["max_level_debug", "release_max_level_info"] }

chrono = "0.4.23"
hex = "0.4.3"
sha2 = "0.10.6"
regex = "1.4.1"
rust-argon2 = "1.0.0"
lazy_static = "1.4.0"
unicode-normalization = "0.1.13"
getrandom = "0.2.8"
time = "0.3.17"

entity = { path = "entity" }
migration = { path = "migration" }

[dependencies.sea-orm]
version = "0.10.6"
default-features = true
features = ["mock", "default", "with-json", "macros", "sqlx-postgres", "runtime-actix-rustls", "chrono", "postgres-array"]

[dev-dependencies]
async-std = { version = "^1", features = ["attributes", "tokio1"] }
reqwest = { version = "0.11.11", features = ["json"] }
once_cell = "1.13.1"
uuid = { version = "1.1.2", features = ["v4"] }
serde_json = "1.0.72"

[dev-dependencies.sqlx]
version = "0.6.1"
default-features = false
features = [
    "runtime-actix-rustls",
    "postgres",
]
