//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.11

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(unique)]
    pub user_id: String,
    pub email: String,
    pub username: String,
    pub pass_hash: String,
    pub email_validated: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub login_blocked_until: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::note::Entity")]
    Note,
    #[sea_orm(has_one = "super::user_authentication::Entity")]
    UserAuthentication,
    #[sea_orm(has_one = "super::user_confirmation::Entity")]
    UserConfirmation,
    #[sea_orm(has_one = "super::user_recovery_password::Entity")]
    UserRecoveryPassword,
    #[sea_orm(has_one = "super::user_security_settings::Entity")]
    UserSecuritySettings,
    #[sea_orm(has_many = "super::user_session::Entity")]
    UserSession,
}

impl Related<super::note::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Note.def()
    }
}

impl Related<super::user_authentication::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserAuthentication.def()
    }
}

impl Related<super::user_confirmation::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserConfirmation.def()
    }
}

impl Related<super::user_recovery_password::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRecoveryPassword.def()
    }
}

impl Related<super::user_security_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSecuritySettings.def()
    }
}

impl Related<super::user_session::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSession.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
